### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by githubBingoChen** [Ugness/PiCANet-Implementation#3]
When I change the path of duts's training set, I get some error like 
torch.backends.cudnn.CuDNNError: 4: CUDNN_STATUS_INTERNAL_ERROR
Exception ctypes.ArgumentError: "argument 1: <type 'exceptions.TypeError'>: Don't know how to convert parameter 1" in <bound method CuDNNHandle.__del__ of <torch.backends.cudnn.CuDNNHandle instance at 0x7fc76508a248>> ignored
Could you upload a guidance that explain how to use your code for convenience?

**Comment by Ugness** [comment]
I am sorry. I didn't see that error before, so it's hard to solve that problem. Can you find the line in my code that the error occured?  I think that you got the error because you don't have gpu to use cuda or cudnn. 
My suggestion is in train.py 20 line,     
device = torch.device("cuda")
to
device = torch.device("cpu")

This is my computing environment
NVIDIA gtx 1080ti
windows 10
python 3.5
pytorch 0.4.0
CUDA 9.0
CUDNN 7.0

And also there are some mismatch cases in DUTS dataset. Please check the dataset carefully.
I hope you solve this problem.
